"""Initial schema - users, conversations, messages

Revision ID: 3b9e667af3a8
Revises: 
Create Date: 2026-04-15 11:49:58.056304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b9e667af3a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_conv_created', ['conversation_id', 'created_at'], unique=False)
        batch_op.create_index('ix_messages_role_intent', ['role', 'intent'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'conversations', ['conversation_id'], ['id'])
        batch_op.drop_index('ix_messages_role_intent')
        batch_op.drop_index('ix_messages_conv_created')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_conversations_user_id'))
        batch_op.drop_column('last_active_at')

    # ### end Alembic commands ###
